### PR TITLE
Merge TSDX

### PR DESCRIPTION
**Pull request by rtrvrtg**

### CODE REVIEW

**Comment by unkleho** [comment]
Hey Geoff, I'm having some issues with the dev example.html - doesn't seem to play for some reason? Is it working for you? I'm running `npm run browsersync`.

**Comment by rtrvrtg** [comment]
@unkleho To be honest, the browsersync preview has always been a bit janky; will see if I can get it fixed up though.

**Comment by unkleho** [comment]
If browsersync is being annoying, could I suggest Parcel? Essentially we create a new example app with its own package.json, replicating how you'd use it in a project.

Example here: https://github.com/unkleho/d3-render/tree/master/example

**Comment by unkleho** [comment]
Just updated Chrome from 84 to 85 and audio is fixed. looks good to me!

**Review by unkleho — APPROVED** [review]
Pretty sure we can gitignore the dist folder later once we publish to npm. But best to leave it in for now as user-app needs it.

**Pull request merged**
